### Site info:
title: Kiam la vespertoj flugas...
tagline: Mia esperante blogo
author: MSaliko
email: mikaelosaliko@gmail.com
description: "un blog sobre linux i més" 
keywords: "Esperanto"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://msaliko.github.io" # the base hostname & protocol for your site
locale: eo

### Personal info and site tools info:
twitter_username: misaliko
github_username:  msaliko
tumblr: msaliko
disqus_shortname: msaliko
favicon:     "/images/favicon.ico"
aboutme: Bonvenon al mia blogo
aboutme_photo: "/images/ogp.png" # your photo.
### google_analytics_key: # put YOUR key here to enable tracking! 

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "eo" # blog sidebar language set, only include: English(en) and Esperanto (eo)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    eo:
      Aboutme: "Pri mi"
      Archives: "Arkivoj"
      Blogroll: "Listo"        
      Categories: "Kategorio"    
      Copyright_Notice: "Aŭtorrajto "
      Recent_Posts: "Novaĵoj"
      Tags: "Etikedoj" 
      Previous: "Antaŭa"
      Next: "Sekva"
      PostedInCategories: "Kategorioj:"   
      Taggedwith: "| Etikedoj:"
      PostDate: "| Dato: "    
      Google_search: "Serĉi"

### llista de pàgines

Blogroll:
    - name: Kiam la vespertoj flugas
      href: https://msaliko.github.io
      title: Kiam la vespertoj flugas
    - name:
      href: 
      title:

### disqus
disqus_short_name: msaliko
disqus_show_comment_count: true 

### Build settings
markdown: kramdown
highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
